"""Persistence interface for AURA.

Postgres/Supabase is the source of truth. A drop-in in-memory implementation
exists so the product runs end-to-end locally without a database; the factory
selects the backend from configuration. Both implementations hydrate full
`AssessmentState` so the engine can resume after a browser refresh.
"""

from __future__ import annotations

from typing import Protocol, runtime_checkable

from ..models.assessment import AssessmentState
from ..models.profile import CandidateProfile
from ..models.result import AssessmentReport, ReadinessResult


@runtime_checkable
class Store(Protocol):
    # --- Profiles ---
    def get_profile(self, user_id: str) -> CandidateProfile | None: ...
    def upsert_profile(self, profile: CandidateProfile) -> CandidateProfile: ...

    # --- Assessments ---
    def create_assessment(self, state: AssessmentState) -> AssessmentState: ...
    def get_assessment(self, assessment_id: str, user_id: str) -> AssessmentState | None: ...
    def list_assessments(self, user_id: str) -> list[AssessmentState]: ...
    def save_assessment(self, state: AssessmentState) -> AssessmentState: ...

    # --- Results & reports ---
    def save_result(self, assessment_id: str, result: ReadinessResult) -> ReadinessResult: ...
    def get_result(self, assessment_id: str, user_id: str) -> ReadinessResult | None: ...
    def list_results(self, user_id: str) -> list[ReadinessResult]: ...
    def save_report(self, assessment_id: str, report: AssessmentReport) -> AssessmentReport: ...
    def get_report(self, assessment_id: str, user_id: str) -> AssessmentReport | None: ...
